name: CI

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: ['8.0', '8.1', '8.2', '8.3']
        silverstripe: [4, 5]
        exclude:
          - php: 8.0
            silverstripe: 5
    env:
      MYSQL_ALLOW_EMPTY_PASSWORD: true
      MYSQL_DATABASE: SS_test
    services:
      mariadb:
        image: mariadb:11
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: true
          MYSQL_DATABASE: SS_test
        ports:
          - 3306:3306

    steps:
      - uses: actions/checkout@v3
      - uses: php-actions/composer@v6
      - name: Install Composer dependencies
        run: composer install --no-progress --no-suggest --prefer-dist --optimize-autoloader
      
      - name: Use SilverStripe v${{ matrix.silverstripe }}
        run: composer require --with-all-dependencies silverstripe/framework "^${{ matrix.silverstripe }}"

      - name: Setup test environment
        run: |
          php -r "copy('.env.testing', '.env');"
